version: 0.0
os: linux
files:
  - source: /
    destination: /
# permissions:
#   - object: /home/ubuntu
#     owner: ubuntu
#     group: ubuntu
#     type:
#       - directory
#       - file
hooks:
  ApplicationStart:
    - location: scripts/start-app.sh
      timeout: 300
      # runas: ubuntu

  # ApplicationStop:
  #   - location: scripts/stop-app.sh
  #     timeout: 300