name: Deploy to S3

on:
  workflow_run:
    workflows: ["CI to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: acebook-team-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'   # optional: defaults to us-east-1
        SOURCE_DIR:     # optional: defaults to entire repository

      # Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

      # Create deployment to CodeDeploy
    - name: AWS Create Deployment to CodeDeploy
      run: |
        aws deploy create-deployment \
          --application-name group2-acebook \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name acebook-group-2-deployment \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=acebook-team-2,key=Dockerfile.zip,bundleType=zip \
