name: Deploy to S3

on:
  workflow_run:
    workflows: ["CI to Docker Hub"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: acebook-team-2
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'   # optional: defaults to us-east-1
        SOURCE_DIR:     # optional: defaults to entire repository

      # Create deployment to CodeDeploy
    - name: AWS Create Deployment
      run: |
        aws deploy create-deployment \
          --application-name acebook-team-2 \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name acebook-group-2-deployment \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=acebook-team-2,bundleType=zip,eTag=ad0536d119627a3229ad106a7cf3b088key=Dockerfile.zip